import Select from 'react-select'
import { MySelect } from '../styles/style';

const countries = [
    { "value": "afganistan", "label": "Afganistan" },
    { "value": "albania", "label": "Albania" },
    { "value": "algeria", "label": "Algeria" },
    { "value": "american samoa", "label": "American Samoa" },
    { "value": "andorra", "label": "Andorra" },
    { "value": "angola", "label": "Angola" },
    { "value": "anguilla", "label": "Anguilla" },
    { "value": "antigua & barbuda", "label": "Antigua & Barbuda" },
    { "value": "argentina", "label": "Argentina" },
    { "value": "armenia", "label": "Armenia" },
    { "value": "aruba", "label": "Aruba" },
    { "value": "australia", "label": "Australia" },
    { "value": "austria", "label": "Austria" },
    { "value": "azerbaijan", "label": "Azerbaijan" },
    { "value": "bahamas", "label": "Bahamas" },
    { "value": "bahrain", "label": "Bahrain" },
    { "value": "bangladesh", "label": "Bangladesh" },
    { "value": "barbados", "label": "Barbados" },
    { "value": "belarus", "label": "Belarus" },
    { "value": "belgium", "label": "Belgium" },
    { "value": "belize", "label": "Belize" },
    { "value": "benin", "label": "Benin" },
    { "value": "bermuda", "label": "Bermuda" },
    { "value": "bhutan", "label": "Bhutan" },
    { "value": "bolivia", "label": "Bolivia" },
    { "value": "bonaire", "label": "Bonaire" },
    { "value": "bosnia & herzegovina", "label": "Bosnia & Herzegovina" },
    { "value": "botswana", "label": "Botswana" },
    { "value": "brazil", "label": "Brazil" },
    { "value": "british indian ocean ter", "label": "British Indian Ocean Ter" },
    { "value": "brunei", "label": "Brunei" },
    { "value": "bulgaria", "label": "Bulgaria" },
    { "value": "burkina faso", "label": "Burkina Faso" },
    { "value": "burundi", "label": "Burundi" },
    { "value": "cambodia", "label": "Cambodia" },
    { "value": "cameroon", "label": "Cameroon" },
    { "value": "canada", "label": "Canada" },
    { "value": "canary islands", "label": "Canary Islands" },
    { "value": "cape verde", "label": "Cape Verde" },
    { "value": "cayman islands", "label": "Cayman Islands" },
    { "value": "central african republic", "label": "Central African Republic" },
    { "value": "chad", "label": "Chad" },
    { "value": "channel islands", "label": "Channel Islands" },
    { "value": "chile", "label": "Chile" },
    { "value": "china", "label": "China" },
    { "value": "christmas island", "label": "Christmas Island" },
    { "value": "cocos island", "label": "Cocos Island" },
    { "value": "colombia", "label": "Colombia" },
    { "value": "comoros", "label": "Comoros" },
    { "value": "congo", "label": "Congo" },
    { "value": "cook islands", "label": "Cook Islands" },
    { "value": "costa rica", "label": "Costa Rica" },
    { "value": "cote divoire", "label": "Cote DIvoire" },
    { "value": "croatia", "label": "Croatia" },
    { "value": "cuba", "label": "Cuba" },
    { "value": "curaco", "label": "Curaco" },
    { "value": "cyprus", "label": "Cyprus" },
    { "value": "czech republic", "label": "Czech Republic" },
    { "value": "denmark", "label": "Denmark" },
    { "value": "djibouti", "label": "Djibouti" },
    { "value": "dominica", "label": "Dominica" },
    { "value": "dominican republic", "label": "Dominican Republic" },
    { "value": "east timor", "label": "East Timor" },
    { "value": "ecuador", "label": "Ecuador" },
    { "value": "egypt", "label": "Egypt" },
    { "value": "el salvador", "label": "El Salvador" },
    { "value": "equatorial guinea", "label": "Equatorial Guinea" },
    { "value": "eritrea", "label": "Eritrea" },
    { "value": "estonia", "label": "Estonia" },
    { "value": "ethiopia", "label": "Ethiopia" },
    { "value": "falkland islands", "label": "Falkland Islands" },
    { "value": "faroe islands", "label": "Faroe Islands" },
    { "value": "fiji", "label": "Fiji" },
    { "value": "finland", "label": "Finland" },
    { "value": "france", "label": "France" },
    { "value": "french guiana", "label": "French Guiana" },
    { "value": "french polynesia", "label": "French Polynesia" },
    { "value": "french southern ter", "label": "French Southern Ter" },
    { "value": "gabon", "label": "Gabon" },
    { "value": "gambia", "label": "Gambia" },
    { "value": "georgia", "label": "Georgia" },
    { "value": "germany", "label": "Germany" },
    { "value": "ghana", "label": "Ghana" },
    { "value": "gibraltar", "label": "Gibraltar" },
    { "value": "great britain", "label": "Great Britain" },
    { "value": "greece", "label": "Greece" },
    { "value": "greenland", "label": "Greenland" },
    { "value": "grenada", "label": "Grenada" },
    { "value": "guadeloupe", "label": "Guadeloupe" },
    { "value": "guam", "label": "Guam" },
    { "value": "guatemala", "label": "Guatemala" },
    { "value": "guinea", "label": "Guinea" },
    { "value": "guyana", "label": "Guyana" },
    { "value": "haiti", "label": "Haiti" },
    { "value": "hawaii", "label": "Hawaii" },
    { "value": "honduras", "label": "Honduras" },
    { "value": "hong kong", "label": "Hong Kong" },
    { "value": "hungary", "label": "Hungary" },
    { "value": "iceland", "label": "Iceland" },
    { "value": "indonesia", "label": "Indonesia" },
    { "value": "india", "label": "India" },
    { "value": "iran", "label": "Iran" },
    { "value": "iraq", "label": "Iraq" },
    { "value": "ireland", "label": "Ireland" },
    { "value": "isle of man", "label": "Isle of Man" },
    { "value": "israel", "label": "Israel" },
    { "value": "italy", "label": "Italy" },
    { "value": "jamaica", "label": "Jamaica" },
    { "value": "japan", "label": "Japan" },
    { "value": "jordan", "label": "Jordan" },
    { "value": "kazakhstan", "label": "Kazakhstan" },
    { "value": "kenya", "label": "Kenya" },
    { "value": "kiribati", "label": "Kiribati" },
    { "value": "korea north", "label": "Korea North" },
    { "value": "korea sout", "label": "Korea Sout" },
    { "value": "kuwait", "label": "Kuwait" },
    { "value": "kyrgyzstan", "label": "Kyrgyzstan" },
    { "value": "laos", "label": "Laos" },
    { "value": "latvia", "label": "Latvia" },
    { "value": "lebanon", "label": "Lebanon" },
    { "value": "lesotho", "label": "Lesotho" },
    { "value": "liberia", "label": "Liberia" },
    { "value": "libya", "label": "Libya" },
    { "value": "liechtenstein", "label": "Liechtenstein" },
    { "value": "lithuania", "label": "Lithuania" },
    { "value": "luxembourg", "label": "Luxembourg" },
    { "value": "macau", "label": "Macau" },
    { "value": "macedonia", "label": "Macedonia" },
    { "value": "madagascar", "label": "Madagascar" },
    { "value": "malaysia", "label": "Malaysia" },
    { "value": "malawi", "label": "Malawi" },
    { "value": "maldives", "label": "Maldives" },
    { "value": "mali", "label": "Mali" },
    { "value": "malta", "label": "Malta" },
    { "value": "marshall islands", "label": "Marshall Islands" },
    { "value": "martinique", "label": "Martinique" },
    { "value": "mauritania", "label": "Mauritania" },
    { "value": "mauritius", "label": "Mauritius" },
    { "value": "mayotte", "label": "Mayotte" },
    { "value": "mexico", "label": "Mexico" },
    { "value": "midway islands", "label": "Midway Islands" },
    { "value": "moldova", "label": "Moldova" },
    { "value": "monaco", "label": "Monaco" },
    { "value": "mongolia", "label": "Mongolia" },
    { "value": "montserrat", "label": "Montserrat" },
    { "value": "morocco", "label": "Morocco" },
    { "value": "mozambique", "label": "Mozambique" },
    { "value": "myanmar", "label": "Myanmar" },
    { "value": "nambia", "label": "Nambia" },
    { "value": "nauru", "label": "Nauru" },
    { "value": "nepal", "label": "Nepal" },
    { "value": "netherland antilles", "label": "Netherland Antilles" },
    { "value": "netherlands", "label": "Netherlands" },
    { "value": "nevis", "label": "Nevis" },
    { "value": "new caledonia", "label": "New Caledonia" },
    { "value": "new zealand", "label": "New Zealand" },
    { "value": "nicaragua", "label": "Nicaragua" },
    { "value": "niger", "label": "Niger" },
    { "value": "nigeria", "label": "Nigeria" },
    { "value": "niue", "label": "Niue" },
    { "value": "norfolk island", "label": "Norfolk Island" },
    { "value": "norway", "label": "Norway" },
    { "value": "oman", "label": "Oman" },
    { "value": "pakistan", "label": "Pakistan" },
    { "value": "palau island", "label": "Palau Island" },
    { "value": "palestine", "label": "Palestine" },
    { "value": "panama", "label": "Panama" },
    { "value": "papua new guinea", "label": "Papua New Guinea" },
    { "value": "paraguay", "label": "Paraguay" },
    { "value": "peru", "label": "Peru" },
    { "value": "phillipines", "label": "Phillipines" },
    { "value": "pitcairn island", "label": "Pitcairn Island" },
    { "value": "poland", "label": "Poland" },
    { "value": "portugal", "label": "Portugal" },
    { "value": "puerto rico", "label": "Puerto Rico" },
    { "value": "qatar", "label": "Qatar" },
    { "value": "republic of montenegro", "label": "Republic of Montenegro" },
    { "value": "republic of serbia", "label": "Republic of Serbia" },
    { "value": "reunion", "label": "Reunion" },
    { "value": "romania", "label": "Romania" },
    { "value": "russia", "label": "Russia" },
    { "value": "rwanda", "label": "Rwanda" },
    { "value": "st barthelemy", "label": "St Barthelemy" },
    { "value": "st eustatius", "label": "St Eustatius" },
    { "value": "st helena", "label": "St Helena" },
    { "value": "st kitts-nevis", "label": "St Kitts-Nevis" },
    { "value": "st lucia", "label": "St Lucia" },
    { "value": "st maarten", "label": "St Maarten" },
    { "value": "st pierre & miquelon", "label": "St Pierre & Miquelon" },
    { "value": "st vincent & grenadines", "label": "St Vincent & Grenadines" },
    { "value": "saipan", "label": "Saipan" },
    { "value": "samoa", "label": "Samoa" },
    { "value": "samoa american", "label": "Samoa American" },
    { "value": "san marino", "label": "San Marino" },
    { "value": "sao tome & principe", "label": "Sao Tome & Principe" },
    { "value": "saudi arabia", "label": "Saudi Arabia" },
    { "value": "senegal", "label": "Senegal" },
    { "value": "seychelles", "label": "Seychelles" },
    { "value": "sierra leone", "label": "Sierra Leone" },
    { "value": "singapore", "label": "Singapore" },
    { "value": "slovakia", "label": "Slovakia" },
    { "value": "slovenia", "label": "Slovenia" },
    { "value": "solomon islands", "label": "Solomon Islands" },
    { "value": "somalia", "label": "Somalia" },
    { "value": "south africa", "label": "South Africa" },
    { "value": "spain", "label": "Spain" },
    { "value": "sri lanka", "label": "Sri Lanka" },
    { "value": "sudan", "label": "Sudan" },
    { "value": "suriname", "label": "Suriname" },
    { "value": "swaziland", "label": "Swaziland" },
    { "value": "sweden", "label": "Sweden" },
    { "value": "switzerland", "label": "Switzerland" },
    { "value": "syria", "label": "Syria" },
    { "value": "tahiti", "label": "Tahiti" },
    { "value": "taiwan", "label": "Taiwan" },
    { "value": "tajikistan", "label": "Tajikistan" },
    { "value": "tanzania", "label": "Tanzania" },
    { "value": "thailand", "label": "Thailand" },
    { "value": "togo", "label": "Togo" },
    { "value": "tokelau", "label": "Tokelau" },
    { "value": "tonga", "label": "Tonga" },
    { "value": "trinidad & tobago", "label": "Trinidad & Tobago" },
    { "value": "tunisia", "label": "Tunisia" },
    { "value": "turkey", "label": "Turkey" },
    { "value": "turkmenistan", "label": "Turkmenistan" },
    { "value": "turks & caicos is", "label": "Turks & Caicos Is" },
    { "value": "tuvalu", "label": "Tuvalu" },
    { "value": "uganda", "label": "Uganda" },
    { "value": "united kingdom", "label": "United Kingdom" },
    { "value": "ukraine", "label": "Ukraine" },
    { "value": "united arab erimates", "label": "United Arab Erimates" },
    { "value": "united states of america", "label": "United States of America" },
    { "value": "uraguay", "label": "Uraguay" },
    { "value": "uzbekistan", "label": "Uzbekistan" },
    { "value": "vanuatu", "label": "Vanuatu" },
    { "value": "vatican city state", "label": "Vatican City State" },
    { "value": "venezuela", "label": "Venezuela" },
    { "value": "vietnam", "label": "Vietnam" },
    { "value": "virgin islands (brit)", "label": "Virgin Islands (Brit)" },
    { "value": "virgin islands (usa)", "label": "Virgin Islands (USA)" },
    { "value": "wake island", "label": "Wake Island" },
    { "value": "wallis & futana is", "label": "Wallis & Futana Is" },
    { "value": "yemen", "label": "Yemen" },
    { "value": "zaire", "label": "Zaire" },
    { "value": "zambia", "label": "Zambia" },
    { "value": "zimbabwe", "label": "Zimbabwe" }
]

export default function SelectCountry() {

    return (
        <MySelect>
            <h3>Country</h3>
            <Select options={countries} />
        </MySelect>
    )
}